### ISSUE TITLE
Devise a Python script to quantify differences in Skywalker output modules

### ISSUE THREAD

**Issue by jeff-cohere** [eagles-project/mam_x_validation#4]
We've been using Skywalker to generate plots for our different codes, and then eyeballing those plots. It would be tremendously useful to have a tool that accepted two Skywalker output modules and emitted a report giving some measures of the differences in the output quantities in these modules. Here's a proposal for such a tool:

1. The tool accepts the names of two skywalker output modules as command line arguments
2. It imports the two skywalker outputs modules and mines them for output variables. Maybe it can also do some simple validation to ensure that the output modules contain data for the same variables.
3. For each output variable, the tool computes some set of error norms (Inf, 1, 2 norms?), perhaps including both absolute and relative measures. We could establish a convention where the first module passed as an argument is the "reference" dataset, for purposes of computing relative error norms.
4. When it has computed all the error norms for the output modules, the tool emits a text file containing a report of the error norms. We can start with a simple plain text file and play around with it. Down the line, if we can think of a workflow that makes use of this information in some appropriate format, we can switch to that format.

@overfelt , how does this sound? Any thoughts?

**Comment by overfelt** [comment]
Jeff,
Sounds good to me.  
jro

**Comment by overfelt** [comment]
There is now a branch jroverf/WIP_DiffToolForSkywalkerFiles that has a little script in it to diff a couple of files.  Right now everything is there except the output is to the screen which could then be directed to an output file or not.  Otherwise there needs to be a way to generate the name of the output file even if it is just hard-coded in the script.

1.  How to find the input python modules (files).  Currently there is a bit of logic to see if the filenames have a path and adds the path to the system path so the module can be loaded.   Maybe this should be removed in favor of the user setting PYTHONPATH?
2. Should there be a tolerance input and a PASSED or FAILED message along with a return code?
3. Any reason to diff the input values also?  Maybe for a check that the files are compatible for diffing?  Right now it just does the norm of any commonly named output fields.

**Comment by jeff-cohere** [comment]
Good questions!

To your questions 1 and 2 (and possibly to specify an output file, for example), I think in order to be flexible about how we construct workflows, maybe we should allow the user to specify these things with flags. Python has a handy [argparse](https://docs.python.org/3/library/argparse.html) module for handling these kinds of flags. I don't know how useful providing a single tolerance is for all output (probably it's test-dependent), but I suppose we can start that way and see what we learn. We could allow a colon-separated set of paths to search for modules with a `-p` option, and allow the user to specify an output file for the report with `-o`, maybe.

To 3: I think validating the input and making sure it's the same is worthwhile, since we're probably assuming that the codes have been run using identical input.

Just my thoughts. The script looks good! Have you tried it out on existing output modules?

**Comment by overfelt** [comment]
I have a single output module that I copied from a skywalker unit that that I have been using to test.  Just copied it and changed a couple of the values in the qoi to get two inputs.
